name: Deploy to ECR
# updated secrets
on: 
  push:
    branches: [ master ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: clo835-ecr-assignment1
        IMAGE_TAG: v0.1
      run: |
        cd application/
        ls -ltra
        # Command to build mysql image
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:mydb_$IMAGE_TAG -f Dockerfile_mysql .
        

        # Command to push mysql image 
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:mydb_$IMAGE_TAG

        # command to build application image
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:myapp_$IMAGE_TAG -f Dockerfile .

        # command to push application image
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:myapp_$IMAGE_TAG
       

          
      